[phases.setup]
nixPkgs = ['php83', 'php83Extensions.gd', 'php83Extensions.zip', 'php83Extensions.pdo_mysql', 'composer']

[phases.build]
cmds = [
    'composer install --optimize-autoloader --no-dev --no-scripts --no-interaction'
]

[start]
cmd = 'php -S 0.0.0.0:$PORT -t public'